apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml --replicas=2
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: todo-api-gateway
  name: todo-api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: todo-api-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml --replicas=2
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/todo-docker-compose-default: "true"
        io.kompose.service: todo-api-gateway
    spec:
      containers:
        - args:
            - sh
            - /home/node/app/start.sh
          env:
            - name: CACHE_SERVICE_URL
            - name: RABBITMQ_URL
            - name: SEARCH_SERVICE_URL
            - name: STORAGE_SERVICE_URL
          image: bruno74t/todo-api-gateway:1.0
          name: todo-api-gateway
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources:
            limits:
              memory: "134217728"
      restartPolicy: Always
