apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml --replicas=2
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: todo-proxy
  name: todo-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: todo-proxy
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml --replicas=2
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/todo-docker-compose-default: "true"
        io.kompose.service: todo-proxy
    spec:
      containers:
        - image: bruno74t/todo-proxy:1.0
          name: todo-proxy
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "134217728"
      restartPolicy: Always
