apiVersion: v1
kind: PersistentVolume
metadata:
 name: elastic-data-pv
 labels:
   type: local
spec:
 storageClassName: manual
 capacity:
   storage: 100Mi
 accessModes:
   - ReadWriteOnce
 hostPath:
   path: "/home/kato/todo-k8s/k8s/elastic-data"
   #Worried about this causing a crashloop
#sudo chmod -R 777 /home/kato/todo-k8s/k8s/elastic-data
