apiVersion: v1
kind: PersistentVolume
metadata:
 name: postgres-data-pv
 labels:
   type: local
spec:
 storageClassName: manual
 capacity:
   storage: 100Mi
 accessModes:
   - ReadWriteOnce
 hostPath:
   path: "/home/kato/todo-k8s/k8s/postgres-data"
